version: '3.6'
services:
  db:
    image: 'postgres:11-alpine'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: phx_todo
      #POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - "7654:5432"
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    # for debugging with pry
    tty: true
    stdin_open: true
    command: iex -S mix phx.server
volumes:
  pgdata: null
